### PR TITLE
Improve tablet ui & material icons

### PR DESCRIPTION
**Pull request by olegazyx**

### CODE REVIEW

**Comment by KernelCrap** [comment]
Sorry for the late answer.

Thank you for your contribution.

It would be great if you could change the icon used for devices (ic_device.png). The icon you have chosen is misleading as a user might expect to be able to cast to the device.

Perhaps there is a server icon of some sort available?

Also, are those icons free to use?

**Comment by olegazyx** [comment]
Sorry for change icons))

All icons from [materialdesignicons.com](https://materialdesignicons.com/) under license [SIL Open Font License v1.1 (OFL-1.1)](https://tldrlegal.com/license/open-font-license-(ofl)-explained)

I'll think about devices icons

**Comment by KernelCrap** [comment]
Great, that icon is much better!

Unfortunately the layout changes breaks the UI on phones if the server has custom icons.
screenshot_20170424-172254

**Comment by olegazyx** [comment]
yeah, I noticed it, but looks OK, imho
I,ve been create new pr, with new icons (devices)

**Pull request closed without merging**
